### ISSUE TITLE
Add Tabbed interface to Data Window

### ISSUE THREAD

**Issue by HansVraga** [USGS-WiM/gl-contaminated-gw#11]
- [x] Add Tabs to bottom Data window, start with 2 " Summary Stats " and "Site Info"

- [x] Initially Populate "Summary stats" with rough info - counts of sites currently displayed on map

- [x] Initially Populate "Site Info" with basic info from site pop-up

**Comment by esmyers** [comment]
https://github.com/USGS-WiM/LIQWIDS/tree/staging/src/app/shared/components

**Comment by HansVraga** [comment]
Will revisit if desired by cooperators
