### ISSUE TITLE
Add newly-discovered Canada services

### ISSUE THREAD

**Issue by esmyers** [USGS-WiM/gl-contaminated-gw#22]
- [x] The logic you need should be in /mainview/map/map.component.ts and /shared/services/map.service.ts

- [x] use the getUSsiteData()  method in the map service as a guide for how to set up the Canada layer

- [x]  If all works well, try to add layerDefs to filter Provinces to show Ontario sites only.

- [x]  use the bindPopup method to get a basic popup working on the layer.

**Comment by ltmetz** [comment]
All done!
