### ISSUE TITLE
Obtain simplified geometry for GL Basin

### ISSUE THREAD

**Issue by HansVraga** [USGS-WiM/gl-contaminated-gw#5]
Use layer created for https://github.com/USGS-WiM/gl-contaminated-gw/issues/3 and create a 'simplified' polygon of entire Great lakes basin

**Comment by ltmetz** [comment]
@esmyers How simple are you thinking? I put a simplified polygon into the project folder. Let me know if it is not simple enough.

**Comment by esmyers** [comment]
Thanks I'll have a look when I get a chance.
